### ISSUE TITLE
I can't synchronize with 0.3.3 or the latest code

### ISSUE THREAD

**Issue by JHong111** [smartbch/smartbch#24]
Can the binary file be given directly?

I can't synchronize with 0.3.3 or the latest code

I[2021-09-09|12:58:06.396] Added peer                                   module=p2p peer="Peer{MConn{18.138.237.114:26656} 9942597c62826d0c25b65203cde1574470653e6e out}"
I[2021-09-09|12:58:06.796] executed block                               module=state height=1 num_valid_txs=0 num_invalid_txs=0
I[2021-09-09|12:58:06.829] committed state                              module=state height=1 num_txs=0 app_hash=2A9219CB627D6D183F8066113DB39ACD81B25A39C3EB023CA4EE1B171511E35F
I[2021-09-09|12:58:06.830] indexed block                                module=txindex height=1
panic: Failed to process committed block (2:B165783F1AD6352F66144533478C17206F7C0F516D1CBB67713848C04448D6CF): wrong Block.Header.AppHash.  Expected 2A9219CB627D6D183F8066113DB39ACD81B25A39C3EB023CA4EE1B171511E35F, got B899D1FB272F0ECBEA60B645D7E4C363ECE9889CF25743BAE14B4D3EB08BABBC

goroutine 3947140 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc01506f340, 0x0)
        /root/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/godata/pkg/mod/github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:110 +0x8c

**Comment by SKlayer** [comment]
You have to delete ./smartbch/data and re sync again.

**Comment by JHong111** [comment]
> You have to delete ./smartbch/data and re sync again.

I have tried it, but it still doesn't work.
When I comment "seeds" in config.json, the program will not be interrupted, but the node will not be found.

**Comment by zxh0** [comment]
Hi @JHong111 
Sorry for the late reply. Could you zip your ~/.smartbchd dir and give us a copy? We need it to find the bug.

**Comment by JHong111** [comment]
发给你的文件中我将"BCH mainnet rpc"注释了


首先我init初始化了文件&nbsp;
	"./smartbchd init mynode --chain-id 0x2710"
其次将配置文件中将app.toml的"# BCH mainnet rpc"换成了我自己的节点，可访问（"可看日志验证"）
删除了init产生的config.toml与genesis.json&nbsp;&nbsp;
	"rm config.toml genesis.json"
拷贝了dot.smartbchd.tgz内的config.toml genesis.json，
	"cp dot.smartbchd/config/config.toml ~/.smartbchd/config/"
	"cp dot.smartbchd/config/genesis.json ~/.smartbchd/config/"


启动命令首先是nohup ./smartbchd start &amp;方式 （同步到最新高度后程序停止）
然后尝试过nohup ./smartbchd start --mainnet-genesis-height=705000 --trace &amp; （同步到最新高度后程序停止）




尝试过将config.toml中的“seeds”注释再次启动 （程序未停止,日志提示找不到节点）
最后一次是将seeds注释后启动的数据（程序未停止,日志提示找不到节点）


日志重定向到nohup.out





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smartbch/smartbch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smartbch/smartbch] I can't synchronize with 0.3.3 or the latest code (#24)





 
Hi @JHong111
 Sorry for the late reply. Could you zip your ~/.smartbchd dir and give us a copy? We need it to find the bug.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

SmartBCH-0.3.3-JHong111.rar (14.44M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=623131643cd47dcb8163093b1033571b0b010857575604071f025556521e510005051c5c035604190407005d52505d0404500557362865675f50431074702d19021f024a051e2f7c5d5f565507024b4653433159&t=exs_ftn_download&code=211d63e4

**Comment by JHong111** [comment]
> Hi @JHong111
> Sorry for the late reply.
> Do you sync from start use v0.3.3? If so, could you zip your ~/.smartbchd dir and give us a copy? We need it to find the bug.

I have replied to the email, don’t know if you have received it?

**Comment by zxh0** [comment]
I received it. Thank you ☺️  
I saw that your bch-mainnet-genesis-height is wrong:

`nohup ./smartbchd start --mainnet-genesis-height=705000 --trace &`

you can delete ~/.smartbchd and redo the steps with  --mainnet-genesis-height=698502:

`nohup ./smartbchd start --mainnet-genesis-height=698502 --trace &`

**Comment by JHong111** [comment]
I was wrong, I understood it wrong, thank you
