### ISSUE TITLE
Fail to Sync mainnet

### ISSUE THREAD

**Issue by miaorao** [smartbch/smartbch#32]
This Node ID: 92bd56d28faf8cfc68a5ba5829931e67e9d1f2da
I[2021-12-01|12:43:17.693] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2021-12-01|12:43:17.693] Starting localClient service                 module=abci-client connection=query impl=localClient
I[2021-12-01|12:43:17.693] Starting localClient service                 module=abci-client connection=snapshot impl=localClient
I[2021-12-01|12:43:17.693] Starting localClient service                 module=abci-client connection=mempool impl=localClient
I[2021-12-01|12:43:17.693] Starting localClient service                 module=abci-client connection=consensus impl=localClient
I[2021-12-01|12:43:17.693] Starting EventBus service                    module=events impl=EventBus
I[2021-12-01|12:43:17.693] Starting PubSub service                      module=pubsub impl=PubSub
I[2021-12-01|12:43:17.693] Starting IndexerService service              module=txindex impl=IndexerService
I[2021-12-01|12:43:17.693] ABCI Handshake App Info                      module=consensus height=1293590 hash=35DB7710CE4214FF1DE6FFDEECA031512F1532EF98D87F748AA59C634E0E4010 software-version= protocol-version=0
I[2021-12-01|12:43:17.693] ABCI Replay Blocks                           module=consensus appHeight=1293590 storeHeight=1293591 stateHeight=1293590
I[2021-12-01|12:43:17.693] Replay last block using real app             module=consensus
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 35DB7710CE4214FF1DE6FFDEECA031512F1532EF98D87F748AA59C634E0E4010, got 623D5993E63633A25928B4803A3C7C0FC040B2CFC267D6639BE292E4981C6BFA

**Comment by helldealer** [comment]
Try release v0.3.5, it fixes th AppHash error
