### ISSUE TITLE
Why was the latest block generated 15 seconds ago?

### ISSUE THREAD

**Issue by llwslc** [smartbch/smartbch#41]
The block time is 6 seconds, but why was the latest block generated 15 seconds ago?

![image](https://user-images.githubusercontent.com/5865414/151509486-d33315d6-376d-479f-a5f9-27ae0709e4db.png)

**Comment by llwslc** [comment]
Hello?

**Comment by silence48** [comment]
hello. i don't contribute to this repo but somehow it emailed me so will reply. difficulties can have swings, what was the issue with it being 17 seconds what is the block time?

**Comment by wangkui0508** [comment]
It is because of the RPC server's latency. The timestamp of a block is the time it gets packed. After that, it needs to be broadcasted, voted, and executed, before a PRC server has the block's record.
Still, it needs more time for your browser to get the block from the RPC server.

**Comment by llwslc** [comment]
![image](https://user-images.githubusercontent.com/5865414/152943111-b14102a7-95b9-4d70-acd4-62d6486667b4.png)

I think my RPC server has received the latest blocks, but the block height in the interface is not the latest, is this correct?

**Comment by wangkui0508** [comment]
The block height in the interface: which interface? Are you using smartscan.cash to connect to your own rpc server?

**Comment by llwslc** [comment]
```
eth_blockNumber
```

I tested all the public rpc services, and all had the same problem, so I run a fullnode and found the same thing. The fullnode log shows the block height, which is 2 blocks higher than the block height of the rpc interface.

**Comment by wangkui0508** [comment]
We also tested it. The RPC is one block later than the log, which is what we expected. 
Because of EBP (you can check our whitepaper to know that is EBP), after block #N commit, it takes another block interval to execute it before it is ready for RPC query. And the execution of block #N is in parallel with the voting process of block #N+1 .
