### ISSUE TITLE
The SmartScan is too simple, is there a plan to improve? 

### ISSUE THREAD

**Issue by llwslc** [smartbch/smartbch#44]
The features provided by the SmartScan is too simple, is there any plan to improve it, or is there any official plan to provide a better scanner?

 It would be better to buy etherscan's service directly.

**Comment by Polve** [comment]
I agree: no way to see contract source, to interact with it, to see parameters & C

Other chains seems all to have the same explorer like https://ftmscan.com/ 

Is the source of that explorer available?

**Comment by wangkui0508** [comment]
Well, this repo is for smartBCH's full-node client. We are only developers for the full-node client and cannot control the explorer. 
Smartscan.cash is an open-source project of Jay. You can open issues at https://github.com/jay-bch/smartbch-explorer 
Or you can talk about possible solutions of explorers at discord or telegram.

**Comment by llwslc** [comment]
Without the support of the smartbch foundation, I don't think there can be any improvement. A good chain is meaningless without official support to build the infrastructure. If it is totally dependent on the community to do the infrastructure, it is a disaster for both developers and holders. That's the worst news I've heard.

**Comment by wangkui0508** [comment]
The main chain of Bitcoin Cash does not have a foundation. And we the smartBCH side chain developers are not backed by any foundation nor control any foundation. These are facts. And I respect your opinion on these facts, no matter what it is.

**Comment by Polve** [comment]
Thanks for the informations, I suppose this issue can be closed.

Anyway, does anybody know if the source for all explorers on other chains (avax, ftm, eth, etc) is available?

Because the explorers there seems all the same, perfectly aligned with all the features, so I suppose there is some central project where they clone from.
