### ISSUE TITLE
How can I do multiple transactions in a block with one address?

### ISSUE THREAD

**Issue by llwslc** [smartbch/smartbch#52]
https://www.smartscan.cash/block/3653497

<img width="892" alt="image" src="https://user-images.githubusercontent.com/5865414/159764347-3031e766-1c08-49cb-9eb4-1f07e5ab8499.png">

When I specify nonce, I get the `bad nonce: tx nonce is larger than the account nonce` error

**Comment by wangkui0508** [comment]
The latest version of smartBCH allows you to do this. However, we will not use them until the upcoming xhedge hardfork.
You can try the Amber testnet, which has a more recent version of smartBCH and has enabled xhedge hardfork.
If you find the same nonce problem on Amber testnet, please let us know.

**Comment by wangkui0508** [comment]
The latest version of smartBCH allows you to do this. However, we will not use them until the upcoming xhedge hardfork.
You can try the Amber testnet, which has a more recent version of smartBCH and has enabled xhedge hardfork.
If you find the same nonce problem on Amber testnet, please let us know.

**Comment by llwslc** [comment]
The main network is inactive for xhedge hard fork, but some nodes can execute transactions after xhedge hard fork

**Comment by llwslc** [comment]
Can you provide an example?

**Comment by llwslc** [comment]
How can I modify the code to pack multiple transactions in one block?
```
  try {
    let nonce = await wallet.getTransactionCount();
    console.log(wallet.address, nonce);

    const tx = {
      to: wallet.address,
      value: 0,
      nonce: nonce++
    };

    wallet.sendTransaction(tx).then(transaction => {
      console.log(nonce, transaction);
    });

    tx.nonce = nonce;
    wallet.sendTransaction(tx).then(transaction => {
      console.log(nonce, transaction);
    });
  } catch (error) {
    console.log(error);
  }
```

**Comment by helldealer** [comment]
you can refer this test code written with golang：https://github.com/smartbch/testkit/blob/main/repeatnonce/repeatnonce.go#L97

**Comment by llwslc** [comment]
https://github.com/smartbch/testkit/blob/main/repeatnonce/repeatnonce.go#L98

Why do I need to sleep 2s. If I don't sleep, it will return the 'bad nonce: tx nonce is larger than the account nonce' error message.

I don't have this problem on other chains.

**Comment by llwslc** [comment]
I tried sleep for 1 ms, and it worked once, sleep for 10 ms, and it worked twice, which is not at all controllable.
